/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cch.view;
import cch.model.Cidade;
import cch.model.CidadeDAO;

/**
 *
 * @author User
 */
public class TelaCidade extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCidade.class.getName());

    /**
     * Creates new form TelaCidade
     */
    public TelaCidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NomeCid = new javax.swing.JTextField();
        ufCid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JButton();
        errorMsg = new javax.swing.JLabel();
        btnListarCidades = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRE UMA CIDADE");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("NOME:");

        NomeCid.setName("nomeCid"); // NOI18N
        NomeCid.addActionListener(this::NomeCidActionPerformed);

        ufCid.setName("uFcid"); // NOI18N
        ufCid.addActionListener(this::ufCidActionPerformed);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("UF:");

        btnCadastro.setText("CADASTRAR");
        btnCadastro.addActionListener(this::btnCadastroActionPerformed);

        btnListarCidades.setText("LISTAR CIDADES");
        btnListarCidades.addActionListener(this::btnListarCidadesActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnListarCidades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastro)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(272, 272, 272)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(errorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NomeCid, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ufCid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ufCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastro)
                    .addComponent(btnListarCidades))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(728, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        
        if(Valida()) {
            
            Cidade cidade = new Cidade(NomeCid.getText(),ufCid.getText());
            
            try {
                
                CidadeDAO cidadeDao = new CidadeDAO();
                Boolean sucess = cidadeDao.Cadastrar(cidade);
                
                if (sucess) {
                    LimpaCampo();
                    errorMsg.setForeground(java.awt.Color.BLACK);
                    errorMsg.setText("CADASTRADO COM SUCESSO!");
                } else {
                   errorMsg.setText("Não foi possível cadastrar tente novamente");
                }
                  
            } catch (Exception e) {
                errorMsg.setText("ERRO ao realizar a chamada do banco " + e.getMessage());
            }
         
        } 

        
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void LimpaCampo () {
        this.NomeCid.setText("");
        this.ufCid.setText("");
    }
    
    private void NomeCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCidActionPerformed
        String Nome = NomeCid.getText();
        errorMsg.setName(Nome);
    }//GEN-LAST:event_NomeCidActionPerformed

    private void ufCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufCidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufCidActionPerformed

    private void btnListarCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCidadesActionPerformed
    Listar telaListar = new Listar("CIDADE");
    telaListar.setLocationRelativeTo(this);
    telaListar.setVisible(true);
    }//GEN-LAST:event_btnListarCidadesActionPerformed
    
    private boolean Valida() {
        
    errorMsg.setVisible(true);

    if ("".equals(NomeCid.getText()) && "".equals(ufCid.getText())) {
        errorMsg.setForeground(java.awt.Color.RED);
        errorMsg.setText("Nome da cidade e UF são campos obrigatórios");
        return false;
    }

    if ("".equals(NomeCid.getText())) {
        errorMsg.setForeground(java.awt.Color.RED);
        errorMsg.setText("Nome da cidade é um campo obrigatório");
        return false;
    }

    if ("".equals(ufCid.getText())) {
        errorMsg.setForeground(java.awt.Color.RED);
        errorMsg.setText("UF da cidade é um campo obrigatório");
        return false;
    }

    String[] ufs = {
        "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES",
        "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR",
        "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC",
        "SP", "SE", "TO"
    };

    boolean ufValida = false;

    for (String estado : ufs) {
        if (estado.equalsIgnoreCase(ufCid.getText().trim())) {
            ufValida = true;
            break;
        }
    }

    if (!ufValida) {
        errorMsg.setForeground(java.awt.Color.RED);
        errorMsg.setText("UF da cidade não é válida!");
        return false;
    }

    errorMsg.setText("");
    return true;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCidade().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NomeCid;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnListarCidades;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ufCid;
    // End of variables declaration//GEN-END:variables
}
